services:
  fileindex:
    image: ghcr.io/dmytrobaida/movie-library:main
    environment:
      DATABASE_URL: "postgresql://movie_user:movie_password@postgres:5432/movie_library?schema=public"
      REDIS_URL: "redis://redis:6379"
      ENABLE_SYNC: "false"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_library
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  stremio:
    image: stremio/server:latest
    ports:
      - 11470:11470

volumes:
  postgres_data:
