services:
  fileindex:
    image: ghcr.io/dmytrobaida/movie-library:main
    environment:
      DATABASE_URL: "postgresql://movie_user:movie_password@postgres:5432/movie_library?schema=public"
      ENABLE_SYNC: "false"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_library
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
