name: "Movie library"

services:
  fileindex:
    platform: linux/amd64
    build:
      context: ../apps/file-index/
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://movie_user:movie_password@postgres:5432/movie_library?schema=public"
      REDIS_URL: "redis:6379"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
