name: "Movie library: Devcontainer"

services:
  devcontainer:
    platform: linux/amd64
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      - ..:/movie-library:cached
      - node-modules:/movie-library/node_modules
    command: sleep infinity

volumes:
  node-modules:
